#! /usr/bin/env bash

if [ -x maze ]; then
    EXECUTABLE="./maze"
elif [ -f maze.js ]; then
    EXECUTABLE="node maze.js"
elif [ -f maze.rb ]; then
    EXECUTABLE="ruby maze.rb"
elif [ -f maze.py ]; then
    EXECUTABLE="python maze.py"
elif [ -f maze.go ]; then
    EXECUTABLE="go run maze.go"
elif [ -f maze.java ]; then
    test maze.class -nt maze.java || javac maze.java
    EXECUTABLE="java maze"
fi

for INPUT_FILE in test-files/input*.txt; do
    OUTPUT_FILE=${INPUT_FILE/input/output}
    
    if [ -f ${INPUT_FILE} -a -f ${OUTPUT_FILE} ]; then
        if cat ${INPUT_FILE} | ${EXECUTABLE} | diff -qbB - ${OUTPUT_FILE} >& /dev/null; then
            echo "`basename ${INPUT_FILE}`: Okay"
        else
            echo "`basename ${INPUT_FILE}`: Failed"
        fi
    fi
done
